/**
 * Example: Integrating generated atlas with Phaser 3
 *
 * This example shows how to load and use sprite atlases
 * generated with simple-sprite-atlas in a Phaser 3 game.
 */

import Phaser from 'phaser';

class GameScene extends Phaser.Scene {
  constructor() {
    super({ key: 'GameScene' });
  }

  preload() {
    // Load the sprite atlases generated by simple-sprite-atlas
    this.load.atlas(
      'characters',
      'assets/characters.png',
      'assets/characters.json'
    );

    this.load.atlas(
      'ui',
      'assets/ui.png',
      'assets/ui.json'
    );

    this.load.atlas(
      'enemies',
      'assets/enemies.png',
      'assets/enemies.json'
    );
  }

  create() {
    // Example 1: Simple sprite creation
    const hero = this.add.sprite(100, 100, 'characters', 'hero/idle_01.png');

    // Example 2: Create walking animation
    this.anims.create({
      key: 'hero-walk',
      frames: this.anims.generateFrameNames('characters', {
        prefix: 'hero/walk_',
        suffix: '.png',
        start: 1,
        end: 8,
        zeroPad: 2
      }),
      frameRate: 10,
      repeat: -1
    });

    // Play the animation
    const walkingHero = this.add.sprite(200, 100, 'characters');
    walkingHero.play('hero-walk');

    // Example 3: Create enemy with different animation
    this.anims.create({
      key: 'enemy-idle',
      frames: this.anims.generateFrameNames('enemies', {
        prefix: 'slime/idle_',
        suffix: '.png',
        start: 1,
        end: 4,
        zeroPad: 2
      }),
      frameRate: 8,
      repeat: -1
    });

    const enemy = this.add.sprite(400, 100, 'enemies');
    enemy.play('enemy-idle');

    // Example 4: Using UI sprites from atlas
    const button = this.add.image(640, 360, 'ui', 'button.png');
    button.setInteractive();
    button.on('pointerdown', () => {
      console.log('Button clicked!');
    });

    // Example 5: Creating a sprite with physics
    const player = this.physics.add.sprite(320, 240, 'characters', 'hero/idle_01.png');
    player.setCollideWorldBounds(true);

    // Example 6: Frame-based sprite states
    const character = this.add.sprite(500, 100, 'characters');

    // Switch between different frames
    character.setFrame('hero/idle_01.png');

    this.time.delayedCall(1000, () => {
      character.setFrame('hero/run_01.png');
    });

    // Example 7: Accessing frame data
    const frameData = this.textures.get('characters').frames;
    console.log('Available frames:', Object.keys(frameData));

    // Example 8: Creating multiple sprites from different directories
    const sprites = [
      'hero/walk_01.png',
      'mage/idle_01.png',
      'warrior/attack_01.png'
    ];

    sprites.forEach((frame, index) => {
      this.add.sprite(100 + index * 100, 300, 'characters', frame);
    });
  }

  update() {
    // Game loop
  }
}

// Phaser game configuration
const config: Phaser.Types.Core.GameConfig = {
  type: Phaser.AUTO,
  width: 800,
  height: 600,
  backgroundColor: '#2d2d2d',
  physics: {
    default: 'arcade',
    arcade: {
      gravity: { x: 0, y: 300 },
      debug: false
    }
  },
  scene: [GameScene]
};

// Create game instance
const game = new Phaser.Game(config);

/**
 * Build script to generate atlases before starting the game:
 *
 * In package.json:
 * {
 *   "scripts": {
 *     "build:atlases": "simple-sprite-atlas -i assets/sprites/characters -o public/assets/characters && simple-sprite-atlas -i assets/sprites/ui -o public/assets/ui",
 *     "dev": "npm run build:atlases && vite",
 *     "build": "npm run build:atlases && vite build"
 *   }
 * }
 */
